# Generated by Django 5.1.7 on 2025-03-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20, unique=True)),
                ('product_price', models.IntegerField()),
                ('product_description', models.CharField(max_length=200)),
                ('product_count', models.IntegerField()),
                ('product_is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
