# Generated by Django 5.1.7 on 2025-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
