# Generated by Django 5.1.7 on 2025-03-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default='CATEGORY_DID_NOT_SET', on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(default='CATEGORY_DID_NOT_SET', max_length=30, primary_key=True, serialize=False),
        ),
    ]
