# Generated by Django 5.1.7 on 2025-04-11 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, unique=True)),
                ('description', models.TextField(default=None)),
                ('city', models.CharField(default=None)),
                ('address', models.TextField(default=None)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None)),
                ('description', models.TextField(default=None)),
                ('salary', models.FloatField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company', to_field='name')),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
    ]
